<!DOCTYPE HTML>
<title>Canvas test: toDataURL.arguments.2 - bug 401795</title>
<!-- Testing: toDataURL ignores extra arguments -->
<script src="/MochiKit/packed.js"></script>
<script src="/tests/SimpleTest/SimpleTest.js"></script>
<link rel="stylesheet" href="/tests/SimpleTest/test.css">
<body>
<canvas id="c" width="100" height="50"><p class="fallback">FAIL (fallback content)</p></canvas>
<script>

SimpleTest.waitForExplicitFinish();
MochiKit.DOM.addLoadEvent(function () {

var canvas = document.getElementById('c');
var ctx = canvas.getContext('2d');

var _thrown_outer = false;
try {

var data = canvas.toDataURL('image/png', 'another argument that should not raise an exception', 'and another');
ok(data =~ /^data:image\/png[;,]/, "data =~ /^data:image\\/png[;,]/");

} catch (e) {
    _thrown_outer = true;
}
todo(!_thrown_outer, 'should not throw exception');

SimpleTest.finish();

});
</script>

